// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwDdLQwZr8hFQ0VcazvgEV3Dtx5J7rg2w',
    appId: '1:1030717132208:web:a4436adedbc65a97565a75',
    messagingSenderId: '1030717132208',
    projectId: 'piggyfinapp',
    authDomain: 'piggyfinapp.firebaseapp.com',
    storageBucket: 'piggyfinapp.appspot.com',
    measurementId: 'G-GK9J6FK6GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0OgIsk-WuBDcO4IIlUzDzErh5DhHoQy4',
    appId: '1:1030717132208:android:6108adf69bf1c9c1565a75',
    messagingSenderId: '1030717132208',
    projectId: 'piggyfinapp',
    storageBucket: 'piggyfinapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjImJKkvj8PpLXj775bCZuLf-O8m8eEFU',
    appId: '1:1030717132208:ios:bf7fec52b23553f8565a75',
    messagingSenderId: '1030717132208',
    projectId: 'piggyfinapp',
    storageBucket: 'piggyfinapp.appspot.com',
    iosBundleId: 'com.example.piggy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjImJKkvj8PpLXj775bCZuLf-O8m8eEFU',
    appId: '1:1030717132208:ios:bf7fec52b23553f8565a75',
    messagingSenderId: '1030717132208',
    projectId: 'piggyfinapp',
    storageBucket: 'piggyfinapp.appspot.com',
    iosBundleId: 'com.example.piggy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwDdLQwZr8hFQ0VcazvgEV3Dtx5J7rg2w',
    appId: '1:1030717132208:web:ce745c55b3f14939565a75',
    messagingSenderId: '1030717132208',
    projectId: 'piggyfinapp',
    authDomain: 'piggyfinapp.firebaseapp.com',
    storageBucket: 'piggyfinapp.appspot.com',
    measurementId: 'G-JLDWS7RR5P',
  );
}
